### ISSUE TITLE
Internet Connection Problems

### ISSUE THREAD

**Issue by shadwalker9** [moonlight-stream/moonlight-docs#24]
So I've connected my laptop to my main PC with moonlight, works great on my local network when both PC's are connected to the same access point, however, when I try to connect across the internet it doesn't seem to work, I do believe I have port forwarding enabled correctly. http://imgur.com/a/HJWqX and here is my ipconfig for the host computer. http://i.imgur.com/4tlCtlE.png now I'm not sure what's going on I've added a rule to windows firewall on both PC's even deactivated it on both and still unable to connect :/ Any help is greatly appreciated

**Comment by cgutman** [comment]
You should remove the port forwarding entries to your external IP address (74.211.x.x). That's not needed and might even cause problems because it's overlapping with the correct port forwarding data.

It looks like your real issue is that there's a typo in your port forwarding of port 47999. It's listed as being from 47998 to 47999 instead of from 47999 to 47999.

**Comment by cgutman** [comment]
You should also leave your "Source Net" field blank.

**Comment by shadwalker9** [comment]
wow you totally called it, works perfect! thank you!
