### ISSUE TITLE
Cannot stream with 4G

### ISSUE THREAD

**Issue by vinilodeon** [moonlight-stream/moonlight-docs#6]
Issue = https://www.youtube.com/watch?v=koou26fn5lA

Router = exposed host
local = works fine
GPU = Nvidia GTX 980 ti
Nvidia Geforce experience 3.0.7.34 (tried older version, no sucess)
Windows 10
Firewall and Antivirus deactivated

want to stream on my Nvidia k1 tablet

any ideas to fix the issue?

Nvidia Corporation files: https://1drv.ms/u/s!AudJExOtNbK_gesloeaiRgCrGw6SXQ

Thanks

**Comment by Krulas** [comment]
I would like to add to this issue, I am unable to stream to my Google Nexus 6 over T-Mobiles network,. I am able to connect locally.  When you say that you are unable to connect over LTE what carrier are you using?

**Comment by somerandoner** [comment]
I had the same issue, and tried almost everything I can think of, until I found d out it wasn't an issue on my cellular services end. What you need to do is login in to your router's administrator settings and forward ports 47984-48010. It varies depending on router but on my Netgear, I went to advanced settings, port forwarding/port triggering, added a custom service, and entered those numbers on the external port range. It's TCP/URL by default for me and that's the port standard you would use.

**Comment by SweepsMT** [comment]
I'm also having problems streaming over 4G

It has worked before perfectly. didn't use it for a little while and now i can't get it to work. since using it last the only 2 things that changed were a router update (i have a fritz!box 3490) & win 10 creators update.

The ports are forwarded as they have always been set up from when i had it working. i've even tried exposed ports. WiFi/Local works fine!

only thing i haven't tried is a vpn or no-ip style kinda thing as im not sure how to set it up properly/haven't looked into but other than that, has anyone got any suggestions ?
