### ISSUE TITLE
Controller issue

### ISSUE THREAD

**Issue by 19clarnoah** [moonlight-stream/moonlight-docs#87]
hey dude! just wanna say, absolutely love your app! works seamlessly with absolutely no lag. but i have a problem. using an Xbox 360 controller paired to my tablet (Samsung Galaxy Tab S3) i can play MOST games with no issue, xinput is seamless. However, i cannot get it to work with Forza Horizon 3. The game simply refuses to acknowledge the controller. On my PC, i play FH3 with my PS4 controller, emulated as a 360 controller with DS4 windows. Basically, both my Xbox controller and PS4 controller are xinput controllers when i use them to play games. WoWMapper, which is a program meant to go with WoW's ConsolePort addon, also works perfectly. Do you know what might be causing FH3 to turn its back on Gamestream's controller input? Any help is greatly appreciated! If it helps anything, I'm using an ASUS GTX 1050Ti 4GB OC Edition.

**Comment by cgutman** [comment]
Is there a chance that DS4Windows is running when Moonlight starts FH3 and it interferes with GeForce Experience's controller emulation? FH3 is supposedly supported since GFE 3.2.2 per https://forums.geforce.com/default/topic/989886/gamestream/universal-windows-platform-uwp-support-for-gamestream-feedback-thread/
