### ISSUE TITLE
pairing request keeps happening

### ISSUE THREAD

**Issue by sebilis** [moonlight-stream/moonlight-docs#88]
Everytime I try to start moonlight and connect to my host PC it keeps asking me to put in the numeric code into the host PC.... Does it not keep certain devices logged in?  How am I supposed to do this if i am miles away from my host PC?  It seems to defeat the purpose of the app.   Any help is appreciated.  TY

**Comment by cgutman** [comment]
This is not normal. What version of GeForce Experience is on your PC and what version of Moonlight are you using?

**Comment by sebilis** [comment]
The newest of both, I just installed both yesterday actually.  I had to install chromes remote access app to be able to remote to my PC and put in the code for moonlight.... Also is it normal for the cursor to be super slow and laggy?  I'm on a pretty decent connection

**Comment by cgutman** [comment]
What's your upload speed on your host PC and your download speed on your client PC? What resolution and frame rate are you trying to stream? What CPU and GPU is in your client PC?

**Comment by sebilis** [comment]
I'm not sure about upload but I have 100mb down I believe Comcast.  I'm trying to run it at 1080p on my client.  My host PC is 980ti and a 4790k.  I didn't think it mattered all that much about hardware specs on the client.  I'm trying it on an older gaming laptop.  Like 6 years old

**Comment by cgutman** [comment]
It sounds like your upload speed is probably too low to stream 1080p60 from your PC. Typically, cable plans like that have somewhere around a 10:1 ratio of download to upload speed, so you probably have around 10 Mb upload (but you can check for sure with speedtest.net). In addition, your connection needs to have low packet loss, which typically means avoiding 2.4 GHz WiFi.

You should reduce your streaming settings to 720p30 and work your way up to see what your connection can handle. You can adjust the bitrate slider manually if the default is still too high.

As for the pairing issue, I suspect it's something specific to your setup, since I haven't heard any reports of this recently. Do you have any extensions that would be deleting cached data or any other reason you can think of that your Chrome data wouldn't be saved?

**Comment by sebilis** [comment]
Ohhh I'm not too sure what would be causing it.  I will definitely try the 720 30 though when I get back.  Thank you !
